spring.datasource.url=jdbc:postgresql://localhost:5432/chronos
spring.datasource.username=postgres
spring.datasource.password=9917225376

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true